finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("printery.urls"))
]

printery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("user-cabinet", views.user_cabinet_view, name="user-cabinet"),
    path("create-order", views.create_order, name="create-order"),
    path("manage", views.manage, name="manage"),
    path("print-schedule", views.print_schedule, name="print-schedule"),

    #api root
    path("orders/<int:order_number>", views.orders_view, name="orders-view"),
    path("orders/all", views.orders_view, name="orders-view"),
]

printery/models.py
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from django.db.models import Max


# Create your models here.
class User(AbstractUser):
    # orders = models.ManyToManyField("Order", blank=True, symmetrical=False, related_name="order")
    phone_number = models.IntegerField(null=True, blank=True)
    company = models.ForeignKey('Company', null=True, blank=True, on_delete=models.CASCADE)
    is_customer = models.BooleanField(default=True)
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.username}"

# class Employee(models.Model):
#     middle_name = models.CharField(max_length=64)
#     position = models.CharField(max_length=64)
#     def __str__(self):
#         return f"{self.first_name}"

#########################################################################

class Company(models.Model):
    name = models.CharField(unique=True, max_length=64)
    address = models.CharField(blank=True, max_length=64)
    city = models.CharField(blank=True, max_length=25)
    postal_code = models.IntegerField(blank=True, null=True)
    country = models.CharField(blank=True, max_length=56)
    email = models.CharField(blank=True, max_length=64)
    phone = PhoneNumberField(null=False, blank=True)
    is_manufacturer = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)

    def __str__(self):
        return self.name

#########################################################################

class Paper(models.Model):
    name = models.CharField(max_length=64)
    TYPE_CHOICES = [
        (None, 'Select...'),
        ('GL', 'Glossy'),
        ('MAT', 'Matte'),
        ('SIL', 'Silk'),
        ('OFF', 'Offset'),
    ]
    type = models.CharField(max_length=3,
        choices=TYPE_CHOICES,
        )
    class Density(models.IntegerChoices):
        D80 = 80, '80 gr/m2'
        D100 = 100, '100 gr/m2'
        D105 = 105, '105 gr/m2'
        D115 = 115, '115 gr/m2'
        D120 = 120, '120 gr/m2'
        D150 = 150, '150 gr/m2'
        D170 = 170, '170 gr/m2'
        D200 = 200, '200 gr/m2'
        D250 = 250, '250 gr/m2'
    density = models.IntegerField(choices=Density.choices)
    width = models.IntegerField()
    height = models.IntegerField()
    manufacturer = models.ManyToManyField(Company, blank=True, related_name="made_by")

    def __str__(self):
        return f"{self.name} {self.get_type_display()} {self.density} gr/m2"

    def serialize(self):
        return {
            "name": self.name,
            "type": self.type,
            "density": self.density,
            "width": self.width,
            "height": self.height,
            # "manufacturer": self.manufacturer
        }

###########################################################################

class Order(models.Model):
    def counter():
        no = Order.objects.aggregate(Max('number'))
        if no == None:
            return 1
        else:
            return no['number__max'] + 1

    number = models.IntegerField(unique=True, default=counter)
    name = models.CharField(blank=True, max_length=16)
    owner = models.ManyToManyField('User', blank=True, related_name="order_owners")

    BOOK = 'BK'
    CALENDAR = 'CL'
    MAGAZINE = 'MZ'
    NEWSPAPER = 'NP'
    FLYERS = 'FL'
    TYPE_CHOICES = [
        (None, "Select..."),
        (BOOK, 'Book'),
        (CALENDAR, 'Calendar'),
        (MAGAZINE, 'Magazine'),
        (NEWSPAPER, 'Newspaper'),
        (FLYERS, 'Flyers')
    ]
    type = models.CharField(max_length=2, choices=TYPE_CHOICES, blank=True)
    circulation = models.IntegerField(null=True, blank=True)

    BINDING_CHOICES = [
        (None, 'Select...'),
        ('GLU', 'Glue'),
        ('STA', 'Staple'),
        ('HAR', 'Hardcover'),
        ('FOL', 'Folding'),
    ]
    binding = models.CharField(blank=True, max_length=4, choices=BINDING_CHOICES,)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)
    delivery_date = models.DateTimeField(null=True, blank=True)

#    def __str__(self):
#        return f"{self.number} {self.name}"

    def serialize(self):
        try:
            block = Part.objects.get(order_id=self.id, part_name='BLO').serialize()
        except Part.DoesNotExist:
            block = ""
        try:
            cover = Part.objects.get(order_id=self.id, part_name='COV').serialize()
        except Part.DoesNotExist:
            cover = ""
        try:
            insert = Part.objects.get(order_id=self.id, part_name='INS').serialize()
        except Part.DoesNotExist:
            insert = "" 

        return {
            "number": self.number,
            "name": self.name,
            "owner": [user.last_name for user in self.owner.all()],
            "type": self.get_type_display(),
            "circulation": self.circulation,
            "binding": self.binding,
            "width": self.width,
            "height": self.height,
            "block": block,
            "cover": cover,
            "insert": insert,
            "created": self.created.strftime("%b %d %Y, %I:%M %p"),
            "due_date": self.due_date.strftime("%b %d %Y, %I:%M %p"),
            "delivery_date": self.delivery_date.strftime("%b %d %Y, %I:%M %p")            
        }

######################################################################################

class Part(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    NAME_CHOICES =[
        ('BLO', 'Block'),
        ('COV', 'Cover'),
        ('INS', 'Insert'),
    ]
    part_name = models.CharField(blank=True, max_length=3, choices=NAME_CHOICES)
    pages = models.IntegerField()
    paper = models.ForeignKey(Paper, null=True, on_delete=models.CASCADE, related_name="paper", blank=True)
    COLOR_CHOICES = [
        (None, 'Select...'),
        ('4_4', '4(CMYK)+4(CMYK)'),
        ('4_0', '4(CMYK)+0'),
        ('1_1', '1(Black)+1(Black)'),
    ]
    color = models.CharField(blank=True, max_length=3, choices=COLOR_CHOICES)

    LAMINATE_CHOICES = [
        (None, 'Select...'),
        ('MAT', 'Matte'),
        ('GL', 'Glossy'),
    ]
    laminate = models.CharField(blank=True, max_length=3, choices=LAMINATE_CHOICES)

    uflak = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.part_name}"

    def serialize(self):
        return {
            "part_name": self.part_name,
            "color": self.color,
            "uflak": self.uflak,
            "order": self.order.id,
            "pages": self.pages,
            "paper": self.paper.serialize()
        }


###############################################################################################

class Printing(models.Model):
    order = models.OneToOneField(Order, on_delete = models.CASCADE, primary_key = True)
    print_date = models.DateField(null=True, blank=True)
    day = models.BooleanField(default=True)
    night = models.BooleanField(default=False)
    circulation = models.IntegerField(null=True, blank=True)
    plates_is_done = models.BooleanField(default=False)

    def __str__(self):
        if self.day:
            return f"{self.print_date} (Day): №{self.order.number}"
        else:
            return f"{self.print_date} (Night): №{self.order.number}"

printery/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator
from django import forms
import json

from printery.models import *
from printery.forms import *
from django.forms import modelformset_factory

# Create your views here.
################################################################################
def index(request):
    if request.user.is_authenticated and request.user.is_customer:
        return HttpResponseRedirect(reverse("user-cabinet"))
    elif request.user.is_authenticated and request.user.is_employee:
        return HttpResponseRedirect(reverse("manage"))
    else:
        return render(request, "printery/index.html", {
        })
################################################################################
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            if User.objects.get(username = username).is_customer:
                return HttpResponseRedirect(reverse("user-cabinet"))
            elif User.objects.get(username = username).is_employee:
                return HttpResponseRedirect(reverse("manage"))
            else:
                return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "printery/login.html", {
                "message": "Invalid username and/or password.", "form": UserForm()
            })
    else:
        return render(request, "printery/login.html", {
        "form": UserForm()
        })

################################################################################
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

################################################################################
def register(request):
    # CompanyFormSet = modelformset_factory(Company, form=CompanyForm, fields=('name',))
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        company_form = CompanyForm(data=request.POST)
        if all([user_form.is_valid(), company_form.is_valid()]):
            company_form.save()
            user = user_form.save(commit=False)
            user.company = Company.objects.get(name = company_form.cleaned_data.get('name'))
            user.set_password(user.password)
            user.save()
            login(request, user)
            if User.objects.get(username = user_form.cleaned_data.get('username')).is_customer:
                return HttpResponseRedirect(reverse("user-cabinet"))
            elif User.objects.get(username = user_form.cleaned_data.get('username')).is_employee:
                return HttpResponseRedirect(reverse("manage"))
        else:
            for field in user_form.errors:
                user_form[field].field.widget.attrs['class'] += ' is-invalid'
            for field in company_form.errors:
                company_form[field].field.widget.attrs['class'] += ' is-invalid'
            return render(request, "printery/register.html", {
                # "message": user_form.errors,
                "user_form": user_form,
                "company_form": company_form,
                # "message_company": company_form.errors,
            })
    else:
        return render(request, "printery/register.html", {
        "user_form": UserForm(),
        "company_form": CompanyForm(),
        })
################################################################################
@login_required(redirect_field_name='index')
def user_cabinet_view(request):
    if request.user.is_customer:
        return render(request, "printery/user-cabinet.html", {
        })
    else:
        return HttpResponseRedirect(reverse("manage"))
################################################################################

@login_required(redirect_field_name='index')
def create_order(request):
    PartsFormSet = modelformset_factory(Part, form=OrderPartsForm, fields=('part_name', 'pages', 'paper', 'color', 'laminate'),max_num=3, extra=3)
    if request.method == "POST":
        order_form = OrderForm(data=request.POST)
        formset = PartsFormSet(request.POST)

        if all([order_form.is_valid(), formset.is_valid()]):
            for form in formset:
                form.save(commit=False)
            formset.save(commit=False)
            order = order_form.save(commit=False)
            order.save()
            order.owner.add(request.user.id)
            order.save()

            instances = formset.save(commit=False)
            for instance in instances:
                instance.order_id = order.id
                instance.save()

            new_order = Order.objects.get(number=order.number)

            return render(request, "printery/create-order.html", {
                'order_form': order_form,
                'parts_form': Part.objects.filter(order_id=new_order.id),
                "successful_submit": True,
                "new_order": order,
            })
        else:
            return render(request, "printery/create-order.html", {
                "message": order_form.errors,
                "message_parts": formset.errors,
                "order_form": order_form,
                "parts_form": formset
            })
    else:

        return render(request, "printery/create-order.html", {
            'order_form': OrderForm(),
            'parts_form': PartsFormSet(queryset=Part.objects.none()),
        })
####################################################################

@csrf_exempt
@login_required
def orders_view(request, order_number = 0):
    if not order_number:
        orders = Order.objects.filter(owner=request.user).order_by("-created").all()
        # parts = Part.objects.filter(order_id=[order.id for order in orders])
        # print("!!!", parts)

        # for order in orders:
        #     for part in Part.objects.filter(order_id=order.id):
        #         # order | part
        #         resp.append(order.serialize() | part.serialize())


        # def ser(order):
        #     for part in Part.objects.filter(order_id=order.id):
        #         print("::::::::::", order.serialize() | part.serialize())
        #         return order.serialize()
        # print("!!!!!!", [order.serialize() for order in orders])
        # return JsonResponse([ser(order) for order in orders], safe=False)

        return JsonResponse([order.serialize() for order in orders], safe=False)

    try:
        order = Order.objects.get(owner=request.user, number=order_number)
    except Order.DoesNotExist:
        return JsonResponse({"error": "Order not found."}, status=404)

    if request.method == "GET":
        return JsonResponse(order.serialize())

#####################################################################
@login_required(redirect_field_name='index')
def manage(request):
    if request.user.is_customer:
        return HttpResponseRedirect(reverse("user-cabinet"))
    return render(request, "printery/manage.html")

################################################################################

@login_required(redirect_field_name='index')
def print_schedule(request):
    return render(request, "printery/manage.html")

printery/templates/printery/create-order.html
{% extends "printery/frontside_layout.html" %}
{% load static %}

{% block window %}
    {% if user.is_authenticated %}
  <div class="flex-lg-1 h-screen overflow-y-lg-auto">

        <header class="position-sticky top-0 overlap-10 bg-surface-primary border-bottom">
          <div class="container-fluid py-4">
            <div class="row align-items-center">
              <div class="col">
                <div class="d-flex align-items-center gap-4">
                  <div><button onclick="location.href = '/user-cabinet';" type="button" class="btn-close text-xs" aria-label="Close"></button></div>
                  <div class="vr opacity-20 my-1"></div>
                  <h1 class="h4 ls-tight">Create a new order</h1>
                </div>
              </div>
              <div class="col-auto">
                <div class="hstack gap-2 justify-content-end">
                  <a href="#" class="text-sm text-muted text-primary-hover font-semibold me-2 d-none d-md-block">
                    <i class="bi bi-question-circle-fill"></i> <span class="d-none d-sm-inline ms-2">Need help?</span>
                  </a>
                  <!--<button type="button" class="btn btn-sm btn-neutral border-base d-none d-md-block"><span>Save and create another</span></button> -->
                   <button type="submit" form="order_form" class="btn btn-sm btn-primary"><span>Save</span></button>
                </div>
              </div>
            </div>
          </div>
        </header>

         <!-- End of header -->

      <main class="py-6 bg-surface-secondary">
        {% include 'printery/form-new-order.html' %}

      <!-- Success order modal -->
        <div class="modal fade" id="modalOrderSuccess" tabindex="-1" aria-labelledby="modalOrderSuccess" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content shadow-3">
                  <div class="modal-header">
                      <div class="icon icon-shape rounded-3 bg-soft-primary text-primary me-4"><i class="bi bi-check-lg"></i></div>
                      <!-- <div> -->
                          <h4 class="mb-1">Thank you for your order!</h4>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          <!-- <small class="d-block text-xs text-muted">Publish and share link with anyone</small> -->
                      <!-- </div> -->
                      <!-- <div class="ms-auto">
                          <div class="form-check form-switch me-n2">
                              <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked="checked" /> <label class="form-check-label" for="flexSwitchCheckChecked"></label>
                          </div>
                      </div> -->
                  </div>
                  <div class="modal-body">
                    <!-- <div class="d-flex align-items-center mb-5"> -->

                      <h4>Order Details</h4>
                        <hr>
                          <p><span class="font-bold">Order ID: #</span>{{ new_order.number }}</p>
                          <p><span class="font-bold">Type: </span>{{ new_order.get_type_display }}</p>
                          <p><span class="font-bold">Finish size (mm): </span>{{ new_order.width }} x {{new_order.height}}</p>
                          <p><span class="font-bold">Circulation: </span>{{ new_order.circulation }}</p>
                          <p><span class="font-bold">Binding: </span>{{ new_order.get_binding_display }}</p>
                          {% for form in parts_form %}
                            <p><span class="font-bold">{{ form.get_part_name_display }}: </span> Pages: {{ form.pages }}, Color: {{ form.get_color_display }}, Paper: {{ form.paper }}</p>
                          {% endfor %}

                          <p><span class="font-bold">Due date: </span>{{ new_order.due_date }}</p>
                          <p><span class="font-bold">Date of delivery: </span>{{ new_order.delivery_date }}</p>
                    <!-- </div>
                       <div>
                          <div class="input-group input-group-inline">
                              <input type="email" class="form-control" placeholder="username" value="https://" /> <span class="input-group-text"><i class="bi bi-clipboard"></i></span>
                          </div>
                          <span class="mt-2 valid-feedback">Looks good!</span>
                      </div>
                  </div>
                  <div class="modal-footer">
                      <div class="me-auto">
                          <a href="#" class="text-sm font-semibold"><i class="bi bi-clipboard me-2"></i>Copy link</a>
                      </div>
                      <button type="button" class="btn btn-sm btn-neutral" data-bs-dismiss="modal">Close</button> <button type="button" class="btn btn-sm btn-success">Share file</button>
                  </div>
              </div>
          </div>
      </div>
      <!-- End of modal success order -->


          {% if successful_submit %}
            <script>
                  document.addEventListener('DOMContentLoaded', function() {
                  // https://getbootstrap.com/docs/5.0/components/modal/#via-javascript
                  let successModal = new bootstrap.Modal(
                    document.getElementById("modalOrderSuccess"),
                    {}
                  );
                  let successModalOnClose = document.getElementById('modalOrderSuccess');
                      successModalOnClose.addEventListener('hidden.bs.modal', function (event) {
                          window.location.href = "/user-cabinet";
                  });
                  // https://getbootstrap.com/docs/5.0/components/modal/#show
                  fetch('/orders/' + {{ new_order.number }})
                  .then(response => response.json())
                  .then(order => {
                    console.log(order);
                    alert("I am an alert box!");
                    successModal.show();
                  })


                })
              </script>
          {%  endif %}

        </main>
</div>

    {% endif %}

{% endblock %}

printery/templates/printery/form-new-order.html
{% block form-new-order %}
{% load static %}
    <!-- Start main -->
    <!-- <main class="py-6 bg-surface-secondary"> -->

      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-8">
            <div class="vstack gap-8 mt-4">
              {% if message or message_parts %}
                  <div class="alert alert-warning" role="alert">{{ order_form.errors }} {{ message_parts }}</div>
              {% endif %}
              <div class="container-fluid max-w-screen-md vstack gap-5">

      <!-- Start form -->
            <form id="order_form" action="{% url 'create-order' %}" method="post">
                {% csrf_token %}
                <div class="row gx-4 gy-5 pb-5">
                  <div class="">
                    Order ID: {{ order_form.number }}
                  </div>
                  <div class="col-md-6"><label class="form-label">Name</label> {{ order_form.name}}
                    <span class="d-block mt-2 text-sm text-muted">Short name of the product</span>
                  </div>
                  <div class="col-md-6"><label class="form-label">Type</label> {{ order_form.type}}
                    <span class="d-block mt-2 text-sm text-muted">Select type of product</span>
                  </div>
                </div>
                <!-- <hr class="my-5" /> -->
                <div class="row gx-4 gy-5 pb-5">
                  <div class="col-md-6"><label class="form-label">Circulation</label>
                    {{ order_form.circulation}}
                  </div>
                  <div class="col-md-6"><label class="form-label">Binding</label>
                    {{ order_form.binding}}
                  </div>
                </div>
                <!-- <hr class="my-5" /> -->
                <div class="row gx-4 gy-5">
                  <div class="col">
                    <div>
                      <label class="form-label">Width (mm)</label>
                      {{ order_form.width}}
                    </div>
                  </div>
                  <div class="cross text-xs col-sm-1 gy-18" ></div>
                  <div class="col">
                    <div>
                      <label class="form-label">Height (mm)</label>
                      {{ order_form.height}}
                    </div>
                  </div>
                </div>
                <br>
                <!-- <hr class="my-10" /> -->

<!-- ************************************************************** -->

            {{ parts_form.management_form }}
            {% for form in parts_form %}
            <div class="collapse show" id="partCard-{%  cycle '1' '2' '3' %}">
            <div class="card " >
              <div>
                <!-- <button type="button" class="part-btn-close" data-bs-dismiss="modal" aria-label="Close"></button> -->
              </div>
            <div class="card-body pb-0">
              <button type="button" class="part-btn-close float-end" data-bs-toggle="collapse" data-bs-target="#partCard-{%  cycle '1' '2' '3' %}" aria-expanded="true" aria-controls="partCard-{%  cycle '0' '1' '2' %}"></button>
              <div class="d-flex justify-content-between">
                <h5 style="text-align: center;">
                  {% cycle 'Block' 'Cover' 'Insert' %}
                </h5>
              </div>
              <div class="row">
                <div class="">
                    {{ form.part_name }}
                </div>
                <div class="col gy-5">
                <div>
                  <label class="form-label">Number of pages </label>
                    {{ form.pages}}
                </div>
                </div>
                <div class="col-sm-3 gy-5">
                <div>
                  <label class="form-label">Printing color</label>
                    {{ form.color}}
                </div>
                </div>
                <div class="col gy-5">
                <div>
                  <label class="form-label">Paper</label>
                    {{ form.paper}}
                </div>
                </div>
              </div>
            </div><br>
            </div>
            </div>
            <br>
            {% endfor %}
            <div class="row gx-4">
                <div class="col-md-6">
                    <div>
                        <label class="form-label">Due date</label>
                        <div class="input-group datepicker">
                            <span class="input-group-text pe-2"><i class="bi bi-calendar"></i> </span>
                            {{ order_form.due_date }}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div>
                        <label class="form-label">Delivery date</label>
                        <div class="input-group datepicker">
                            <span class="input-group-text pe-2"><i class="bi bi-calendar"></i> </span>
                            {{ order_form.delivery_date }}
                            <!-- <input type="text" class="form-control flatpickr-input" placeholder="Select date" data-input /> -->
                        </div>
                    </div>
                </div>
            </div>

                <hr class="my-10" />
                <div><label class="form-label">Description</label>
                  <textarea class="form-control" placeholder="order description ..." rows="2"></textarea>
                  </div>
                <hr class="my-5" />

                <button type="submit" form="order_form" class="btn btn-sm btn-primary"><span>Save</span></button>
            </form>
              </div>
            </div>
          </div>

{% include 'printery/user-sidebar-right.html' %}

        </div>
      </div>
    <!-- </main> -->
    <!-- End main -->
{% endblock %}

printery/templates/printery/index.html
{% extends "printery/layout.html" %}

{% block body %}
{% load static %}

{% if user.is_authenticated %}





{% endif %}
{% endblock %}

printery/templates/printery/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Printery{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'printery/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'printery/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'printery/css/sidebars.css' %}">

        {% block script %}
        <script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
        <script src="{% static 'printery/scripts.js' %}"></script>
        {% endblock %}
    </head>
    <body>
      <nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
      <a class="navbar-brand" href="{% url 'index' %}">Printery</a>
      <ul class="nav me-auto">
        <li class="nav-item"><a href="#" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link link-dark px-2">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link link-dark px-2">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link link-dark px-2">About</a></li>
      </ul>
      <ul class="nav">
        {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="profile/{{ user.username }}"><strong>Hi, {{ user.username }}!</strong></a></li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link link-dark px-2">Logout</a></li>
        {% else %}
            <li class="nav-item"><a href="{% url 'login' %}" class="nav-link link-dark px-2">Login</a></li>
            <li class="nav-item"><a href="{% url 'register' %}" class="nav-link link-dark px-2">Register</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>

        <script src="{% static 'printery/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'printery/js/sidebars.js' %}"></script>
    </body>
</html>